#ifndef CLOTHO_POWERSET_CONFIG_HPP_
#define CLOTHO_POWERSET_CONFIG_HPP_

#include "clotho/config.h"

#ifndef BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS
#define BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS
#define UNDEF_FRIEND
#endif  // BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS

#endif  // CLOTHO_POWERSET_CONFIG_HPP_
